### ISSUE TITLE
Panic while shutting down

### ISSUE THREAD

**Issue by dvdplm** [paritytech/substrate-archive#107]
Just ran into this:

```
    Running `target/release/polkadot-archive -c my_conf.toml --chain=polkadot`
[12:44] INFO Running migrations for postgres://postgres:123@localhost:5432/polkadot-db
[12:44] INFO Open RocksDB at /home/dvdplm/.local/share/polkadot/chains/polkadot/db, state column budget: 3686 MiB, others(11) column cache: 41 MiB
[12:44] INFO Native Version: NativeVersion { runtime_version: RuntimeVersion { spec_name: RuntimeString::Borrowed("polkadot"), impl_name: RuntimeString::Borrowed("parity-polkadot"), authoring_version: 0, spec_version: 23, impl_version: 0, apis: [([223, 106, 203, 104, 153, 7, 96, 155], 3), ([55, 227, 151, 252, 124, 145, 245, 228], 1), ([64, 254, 58, 212, 1, 248, 149, 154], 4), ([210, 188, 152, 151, 238, 208, 143, 21], 2), ([247, 139, 39, 139, 229, 63, 69, 76], 2), ([175, 44, 2, 151, 162, 62, 109, 61], 3), ([237, 153, 197, 172, 178, 94, 237, 245], 2), ([203, 202, 37, 227, 159, 20, 35, 135], 2), ([104, 122, 212, 74, 211, 127, 3, 194], 1), ([171, 60, 5, 114, 41, 31, 235, 139], 1), ([188, 157, 137, 144, 79, 91, 146, 63], 1), ([55, 200, 187, 19, 80, 169, 162, 168], 1)], transaction_version: 5 }, can_author_with: {} }
[12:44] INFO Running archive for chain `polkadot` 🔗, implemention `parity-polkadot`. Latest known runtime version: 25. Latest finalized block 0xadb0…5248 🛡️
[12:44] INFO 🧘 Restoring missing storage entries... (This could take a few minutes)
[12:44] INFO 1 missing blocks
[12:44] INFO Took 810.840108ms to load 1 blocks
[12:44] INFO Inserted
[12:44] INFO Took 3.041877897s to load 283465 blocks
[12:44] INFO Getting metadata for hash 08aad1540d95e5aedf7dc65c627b4c7094626b78512a74ce482a82fd1beca5fc, version 25
[12:44] INFO NATIVE CALL true
[12:44] INFO Contextual CALL, executor
[12:44] INFO NATIVE CALL true
[12:44] INFO Contextual CALL, executor
^C[12:44] INFO Restoring 26 missing storage entries...
[12:44] INFO Storage restored
[12:44] INFO Traces dying
[12:44] INFO 🧘 waiting for last storage insert...
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/dvdplm/work/substrate-archive/src/actors/workers/database.rs:104:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[12:44] ERROR One of the pooled db actors has disconnected. could not send message.
thread '<unnamed>' panicked at 'One Shot', /home/dvdplm/work/substrate-archive/src/actors/actor_pool.rs:118:65
thread '<unnamed>' panicked at 'task has failed', /home/dvdplm/.cargo/registry/src/github.com-1ecc6299db9ec823/multitask-0.2.0/src/lib.rs:166:55
```

This was on the `state-tracing` branch and I hit Ctrl-c to stop the daemon. Had to `kill -9` it to get it to exit.

**Comment by insipx** [comment]
#254 removed actor pool, so this issue should be fixed
